version: '3.7'

services:
  server:
    volumes:
      - static:/static
    env_file:
      - .env
    build:
      context: .
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    command: [ "npm", "start" ]
    stdin_open: true
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    depends_on:
      - server

volumes:
  static: