# Generated by Django 3.2 on 2021-05-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Главная категория')),
            ],
            options={
                'verbose_name': 'Заглавные категории товаров',
                'verbose_name_plural': 'Заглавные категории товаров',
                'db_table': 'main_category',
            },
        ),
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('providers_name', models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Провайдеры данных',
                'verbose_name_plural': 'Провайдеры данных',
                'db_table': 'providers',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка')),
                ('sub_category', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Подкатегория')),
            ],
            options={
                'verbose_name': 'Подкатегории товаров',
                'verbose_name_plural': 'Подкатегории товаров',
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Название товара')),
                ('article', models.CharField(blank=True, default='', max_length=15, null=True, verbose_name='article')),
                ('price', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Цена')),
                ('price_rec', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Rec цена')),
                ('price_opt', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Оптовая цена')),
                ('currency', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='Валюта')),
                ('product_id', models.CharField(blank=True, default='', max_length=10, null=True, verbose_name='ID')),
                ('url', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ссылка на товар')),
                ('picture', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='Ссылка на товар')),
                ('description', models.TextField(blank=True, default='', null=True, verbose_name='Описание товара')),
                ('available', models.BooleanField(blank=True, default=False, null=True, verbose_name='Доступно сейчас')),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop_products.subcategory', verbose_name='Категории')),
                ('provider', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop_products.providers', verbose_name='Провайдер')),
            ],
            options={
                'verbose_name': 'Продукты',
                'verbose_name_plural': 'Продукты',
                'db_table': 'products',
            },
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shop_products.maincategory', verbose_name='заглавные категория')),
                ('sub_category', models.ManyToManyField(blank=True, to='shop_products.SubCategory', verbose_name='подкатегории')),
            ],
            options={
                'verbose_name': 'Категории товаров',
                'verbose_name_plural': 'Категории товаров',
                'db_table': 'categories',
            },
        ),
    ]
